apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: three-tier
spec: 
  accessModes:  
    - ReadWriteOnce
  # تم تغيير القيمة من "" إلى gp2
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
